import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";

export default {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)", ...defaultTheme.fontFamily.sans],
        brand: ["var(--font-brand)", ...defaultTheme.fontFamily.sans],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
        },
        sidebar: "var(--sidebar)",
        "sidebar-foreground": "var(--sidebar-foreground)",
        "sidebar-primary": "var(--sidebar-primary)",
        "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
        "sidebar-accent": "var(--sidebar-accent)",
        "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-ring": "var(--sidebar-ring)",
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        bg: {
          1: "var(--bg-1)",
          2: "var(--bg-2)",
          3: "var(--bg-3)",
          4: "var(--bg-4)",
          5: "var(--bg-5)",
        },
        "border-color": {
          1: "var(--border-1)",
          2: "var(--border-2)",
        },
        fg: {
          1: "var(--fg-1)",
          2: "var(--fg-2)",
          3: "var(--fg-3)",
          4: "var(--fg-4)",
        },
        purple: {
          1: "var(--purple-1)",
          2: "var(--purple-2)",
          3: "var(--purple-3)",
          4: "var(--purple-4)",
        },
        blue: {
          1: "var(--blue-1)",
          2: "var(--blue-2)",
          3: "var(--blue-3)",
          4: "var(--blue-4)",
        },
        gho: {
          1: "var(--gho-1)",
        },
        "accent-color": {
          red: "var(--red)",
          blue: "var(--blue)",
          purple: "var(--purple)",
          green: "var(--green)",
          yellow: "var(--yellow)",
        },
        focus: "var(--focus)",
      },
      fontSize: {
        "step--2": "var(--step--2)",
        "step--1": "var(--step--1)",
        "step-0": "var(--step-0)",
        "step-1": "var(--step-1)",
        "step-2": "var(--step-2)",
        "step-3": "var(--step-3)",
        "step-4": "var(--step-4)",
        "step-5": "var(--step-5)",
        "step-6": "var(--step-6)",
      },
      spacing: {
        "space-3xs": "var(--space-3xs)",
        "space-2xs": "var(--space-2xs)",
        "space-xs": "var(--space-xs)",
        "space-s": "var(--space-s)",
        "space-m": "var(--space-m)",
        "space-l": "var(--space-l)",
        "space-xl": "var(--space-xl)",
        "space-2xl": "var(--space-2xl)",
        "space-3xl": "var(--space-3xl)",
        "space-s-m": "var(--space-s-m)",
        "space-s-l": "var(--space-s-l)",
        "space-m-l": "var(--space-m-l)",
        "space-l-xl": "var(--space-l-xl)",
        "space-l-2xl": "var(--space-l-2xl)",
        "space-xl-2xl": "var(--space-xl-2xl)",
        "space-3xl-4xl": "var(--space-3xl-4xl)",
      },
      letterSpacing: {
        tighter: "-0.075rem",
        tight: "-0.48px",
        snug: "-0.33px",
        normal: "-0.18px",
        caption: "-0.00563rem",
        body: "-0.09px",
      },
      lineHeight: {
        prose: "150%",
        heading: "135%",
        tight: "125%",
        display: "105%",
      },
      borderRadius: {
        pill: "6.1875rem",
        card: "1rem",
        sm: "calc(var(--radius) - 4px)",
        md: "calc(var(--radius) - 2px)",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 4px)",
      },
      boxShadow: {
        card: "0 0 0 1px var(--shadow-stroke-2), 0 8px 40px var(--shadow-high)",
        overlay: "0 0 0 1px var(--shadow-stroke-2), 0 6px 32px var(--shadow-high)",
        btn: "0 0 0 1.5px var(--shadow-stroke-1)",
        "btn-hover": "0 0 0 1.5px var(--shadow-stroke-2)",
      },
      keyframes: {
        "pulse-ring": {
          "0%": { transform: "scale(0)", opacity: "0" },
          "35%": { opacity: "0.7" },
          "70%": { transform: "scale(2.5)", opacity: "0" },
          "100%": { transform: "scale(0)", opacity: "0" },
        },
        "pulse-dot": {
          "0%": { transform: "scale(1)" },
          "35%": { transform: "scale(1.2)" },
          "70%": { transform: "scale(1)" },
          "100%": { transform: "scale(1)" },
        },
        slide: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "slide-footer-line": {
          "0%": { backgroundPosition: "0 0" },
          "70%": { backgroundPosition: "0 0" },
          "100%": { backgroundPosition: "100% 0" },
        },
      },
      animation: {
        "pulse-ring": "pulse-ring 2s ease-out infinite both",
        "pulse-dot": "pulse-dot 2s ease-out infinite both",
        slide: "slide 20s linear infinite both",
        "slide-footer-line": "slide-footer-line 6s ease-in-out infinite",
      },
      screens: {
        xs: "520px",
        sm: "40rem",
        md: "48rem",
        lg: "64rem",
        xl: "80rem",
        "2xl": "86rem",
      },
    },
  },
  plugins: [],
} satisfies Config;
